import 'tailwindcss/tailwind.css'

export const metadata = {
  title: 'Maricopa Senior Living',
  description: 'Generated by Next + Sanity',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
