/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Logo = {
  asset?: SanityImageAssetReference;
  media?: unknown; // Unable to locate the referenced type "logo.media" in schema
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  _type: "image";
};

export type PageBuilder = Array<
  | ({
      _key: string;
    } & Hero)
  | ({
      _key: string;
    } & RichText)
  | ({
      _key: string;
    } & MediaText)
  | ({
      _key: string;
    } & CallToAction)
  | ({
      _key: string;
    } & FeatureList)
  | ({
      _key: string;
    } & Faq)
  | ({
      _key: string;
    } & Video)
  | ({
      _key: string;
    } & Disclaimer)
  | ({
      _key: string;
    } & Alert)
  | ({
      _key: string;
    } & QuickLinks)
  | ({
      _key: string;
    } & CategoryBrowse)
  | ({
      _key: string;
    } & ResourceHighlight)
  | ({
      _key: string;
    } & ArticleHighlight)
  | ({
      _key: string;
    } & Steps)
  | ({
      _key: string;
    } & ContactSection)
  | ({
      _key: string;
    } & Location)
  | ({
      _key: string;
    } & Testimonial)
  | ({
      _key: string;
    } & Partners)
  | ({
      _key: string;
    } & StayConnected)
>;

export type StayConnected = {
  _type: "stayConnected";
  headline: string;
  body?: string;
  actions?: Array<
    {
      _key: string;
    } & Link
  >;
  embedPlaceholder?: string;
};

export type Partners = {
  _type: "partners";
  headline: string;
  intro?: string;
  items?: Array<{
    name: string;
    logo?: Logo;
    url?: string;
    _type: "partner";
    _key: string;
  }>;
};

export type Testimonial = {
  _type: "testimonial";
  quote: string;
  attribution: string;
  role?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type Location = {
  _type: "location";
  headline: string;
  address: string;
  hours?: Array<
    {
      _key: string;
    } & DayAndTime
  >;
  directionsUrl?: string;
  notes?: string;
};

export type ContactSection = {
  _type: "contactSection";
  headline: string;
  intro?: PortableText;
  phone?: string;
  email?: string;
  actions?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type Steps = {
  _type: "steps";
  headline: string;
  intro?: string;
  items?: Array<{
    title: string;
    description?: string;
    _type: "step";
    _key: string;
  }>;
};

export type ArticleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "article";
};

export type ArticleHighlight = {
  _type: "articleHighlight";
  headline: string;
  intro?: string;
  articles?: Array<
    {
      _key: string;
    } & ArticleReference
  >;
};

export type ResourceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "resource";
};

export type ResourceHighlight = {
  _type: "resourceHighlight";
  headline: string;
  intro?: string;
  resources?: Array<
    {
      _key: string;
    } & ResourceReference
  >;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type CategoryBrowse = {
  _type: "categoryBrowse";
  headline: string;
  intro?: string;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
};

export type QuickLinks = {
  _type: "quickLinks";
  headline: string;
  intro?: string;
  links?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type Alert = {
  _type: "alert";
  severity: "info" | "warning" | "urgent";
  headline: string;
  body: string;
  actions?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type Disclaimer = {
  _type: "disclaimer";
  tone: "info" | "warning";
  title?: string;
  body: PortableText;
};

export type Video = {
  _type: "video";
  title: string;
  description?: string;
  url: string;
};

export type Faq = {
  _type: "faq";
  headline?: string;
  items?: Array<{
    question: string;
    answer: PortableText;
    _type: "faqItem";
    _key: string;
  }>;
};

export type FeatureList = {
  _type: "featureList";
  headline: string;
  intro?: string;
  features?: Array<{
    title: string;
    description?: string;
    _type: "feature";
    _key: string;
  }>;
};

export type CallToAction = {
  _type: "callToAction";
  headline: string;
  body?: string;
  actions?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type MediaText = {
  _type: "mediaText";
  headline: string;
  body?: PortableText;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  mediaPlacement?: "start" | "end";
  actions?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type RichText = {
  _type: "richText";
  title?: string;
  content: PortableText;
};

export type Hero = {
  _type: "hero";
  headline: string;
  intro?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  actions?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type ExternalLink = {
  _type: "externalLink";
  title: string;
  description?: string;
  url: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type FileAttachment = {
  _type: "fileAttachment";
  title: string;
  description?: string;
  file: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
};

export type TimeValue =
  | "00:00"
  | "00:30"
  | "01:00"
  | "01:30"
  | "02:00"
  | "02:30"
  | "03:00"
  | "03:30"
  | "04:00"
  | "04:30"
  | "05:00"
  | "05:30"
  | "06:00"
  | "06:30"
  | "07:00"
  | "07:30"
  | "08:00"
  | "08:30"
  | "09:00"
  | "09:30"
  | "10:00"
  | "10:30"
  | "11:00"
  | "11:30"
  | "12:00"
  | "12:30"
  | "13:00"
  | "13:30"
  | "14:00"
  | "14:30"
  | "15:00"
  | "15:30"
  | "16:00"
  | "16:30"
  | "17:00"
  | "17:30"
  | "18:00"
  | "18:30"
  | "19:00"
  | "19:30"
  | "20:00"
  | "20:30"
  | "21:00"
  | "21:30"
  | "22:00"
  | "22:30"
  | "23:00"
  | "23:30";

export type DayAndTime = {
  _type: "dayAndTime";
  day:
    | "Monday"
    | "Tuesday"
    | "Wednesday"
    | "Thursday"
    | "Friday"
    | "Saturday"
    | "Sunday";
  opensAt: TimeValue;
  closesAt: TimeValue;
};

export type PortableText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        openInNewTab?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      caption?: string;
      _type: "image";
      _key: string;
    }
  | {
      asset?: SanityFileAssetReference;
      media?: unknown;
      description: string;
      _type: "attachment";
      _key: string;
    }
>;

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type Link = {
  _type: "link";
  label: string;
  linkType: "internal" | "external";
  internalLink?:
    PageReference | ArticleReference | ResourceReference | CategoryReference;
  externalUrl?: string;
  openInNewTab?: boolean;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  main?: Array<
    {
      _key: string;
    } & Link
  >;
  footer?: Array<
    {
      _key: string;
    } & Link
  >;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteTitle: string;
  siteDescription?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  footerBlurb?: string;
  phone?: string;
  email?: string;
  address?: string;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Tag = {
  _id: string;
  _type: "tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
  seo?: Seo;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type TagReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag";
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  publishedAt: string;
  author?: AuthorReference;
  excerpt?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  body: PortableText;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  tags?: Array<
    {
      _key: string;
    } & TagReference
  >;
  isArchived?: boolean;
  legacyPostId?: string;
  seo?: Seo;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  bio?: PortableText;
};

export type Resource = {
  _id: string;
  _type: "resource";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  kind: "directory" | "guide";
  title: string;
  slug: Slug;
  summary?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  tags?: Array<
    {
      _key: string;
    } & TagReference
  >;
  website?: string;
  phone?: string;
  email?: string;
  address?: string;
  businessHours?: Array<
    {
      _key: string;
    } & DayAndTime
  >;
  eligibility?: PortableText;
  directoryDescription?: PortableText;
  notes?: PortableText;
  body?: PortableText;
  attachments?: Array<
    {
      _key: string;
    } & FileAttachment
  >;
  externalLinks?: Array<
    {
      _key: string;
    } & ExternalLink
  >;
  seo?: Seo;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  pageBuilder?: PageBuilder;
  seo?: Seo;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  pageBuilder?: PageBuilder;
  seo?: Seo;
};

export type SanityAssistInstructionTask = {
  _type: "sanity.assist.instructionTask";
  path?: string;
  instructionKey?: string;
  started?: string;
  updated?: string;
  info?: string;
};

export type SanityAssistTaskStatus = {
  _type: "sanity.assist.task.status";
  tasks?: Array<
    {
      _key: string;
    } & SanityAssistInstructionTask
  >;
};

export type SanityAssistSchemaTypeAnnotations = {
  _type: "sanity.assist.schemaType.annotations";
  title?: string;
  fields?: Array<
    {
      _key: string;
    } & SanityAssistSchemaTypeField
  >;
};

export type SanityAssistOutputType = {
  _type: "sanity.assist.output.type";
  type?: string;
};

export type SanityAssistOutputField = {
  _type: "sanity.assist.output.field";
  path?: string;
};

export type AssistInstructionContextReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "assist.instruction.context";
};

export type SanityAssistInstructionContext = {
  _type: "sanity.assist.instruction.context";
  reference: AssistInstructionContextReference;
};

export type AssistInstructionContext = {
  _id: string;
  _type: "assist.instruction.context";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  context?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityAssistInstructionUserInput = {
  _type: "sanity.assist.instruction.userInput";
  message: string;
  description?: string;
};

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }
    | ({
        _key: string;
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string;
      } & SanityAssistInstructionContext)
    | ({
        _key: string;
      } & SanityAssistInstructionUserInput)
  >;
  style?: "normal";
  listItem?: never;
  markDefs?: null;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityAssistInstructionFieldRef = {
  _type: "sanity.assist.instruction.fieldRef";
  path?: string;
};

export type SanityAssistInstruction = {
  _type: "sanity.assist.instruction";
  prompt?: SanityAssistInstructionPrompt;
  icon?: string;
  title?: string;
  userId?: string;
  createdById?: string;
  output?: Array<
    | ({
        _key: string;
      } & SanityAssistOutputField)
    | ({
        _key: string;
      } & SanityAssistOutputType)
  >;
};

export type SanityAssistSchemaTypeField = {
  _type: "sanity.assist.schemaType.field";
  path?: string;
  instructions?: Array<
    {
      _key: string;
    } & SanityAssistInstruction
  >;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Logo
  | PageBuilder
  | StayConnected
  | Partners
  | Testimonial
  | Location
  | ContactSection
  | Steps
  | ArticleReference
  | ArticleHighlight
  | ResourceReference
  | ResourceHighlight
  | CategoryReference
  | CategoryBrowse
  | QuickLinks
  | Alert
  | Disclaimer
  | Video
  | Faq
  | FeatureList
  | CallToAction
  | MediaText
  | RichText
  | Hero
  | ExternalLink
  | SanityFileAssetReference
  | FileAttachment
  | TimeValue
  | DayAndTime
  | PortableText
  | PageReference
  | Link
  | Seo
  | Navigation
  | Settings
  | SanityImageCrop
  | SanityImageHotspot
  | Tag
  | Slug
  | Category
  | AuthorReference
  | TagReference
  | Article
  | Author
  | Resource
  | Page
  | HomePage
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
